# -*- coding: utf-8 -*-
"""Crop_Streamlit

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hQWTXaQg7gJGQsRb67srNqbNxlPXzAV6
"""

import streamlit as st
import tensorflow as tf

@st.cache(allow_output_mutation=True)
def load_model():
    model = tf.keras.models.load_model('/content/CropDetect.h5')
    return model

model = load_model()

st.write("# Crop Detection System")

file = st.file_uploader("Choose Crop photo from computer", type=["jpg", "png"])

import cv2
from PIL import Image, ImageOps
import numpy as np

def import_and_predict(image_data, model):
    size = (224, 224)
    image = ImageOps.fit(image_data, size, Image.ANTIALIAS)
    img = np.asarray(image)
    img_reshape = img[np.newaxis, ...]
    prediction = model.predict(img_reshape)
    return prediction

if file is None:
    st.text("Please upload an image file")
else:
    image = Image.open(file)
    st.image(image, use_column_width=True)
    prediction = import_and_predict(image, model)

    class_names = [
        'Cherry', 'Coffee-plant', 'Cucumber', 'Fox_nut(Makhana)', 'Lemon',
        'Olive-tree', 'Pearl_millet(bajra)', 'Tobacco-plant', 'almond', 'banana',
        'cardamom', 'chilli', 'clove', 'coconut', 'cotton', 'gram', 'jowar',
        'jute', 'maize', 'mustard-oil', 'papaya', 'pineapple', 'rice', 'soyabean',
        'sugarcane', 'sunflower', 'tea', 'tomato', 'vigna-radiati(Mung)', 'wheat'
    ]

    string = "OUTPUT: " + class_names[np.argmax(prediction)]
    st.success(string)
