# -*- coding: utf-8 -*-
"""Crop_Streamlit

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hQWTXaQg7gJGQsRb67srNqbNxlPXzAV6
"""

import streamlit as st
import tensorflow as tf
import cv2
from PIL import Image,ImageOps
import numpy as np


@st.cache(allow_output_mutation=True)
def load_model():
  model=tf.keras.models.load_model('CropDetect.hdf5')
  return model
model=load_model()
st.write("""
# Crop Detection System"""
)
file=st.file_uploader("Choose a crop photo from computer",type=["jpg","png"])

def import_and_predict(image_data,model):
    size=(224,224)
    image=ImageOps.fit(image_data,size,Image.Resampling.LANCZOS)
    img=np.asarray(image)
    img_reshape=img[np.newaxis,...]
    prediction=model.predict(img_reshape)
    return prediction
if file is None:
    st.text("Please upload an image file")
else:
    image=Image.open(file)
    st.image(image,use_column_width=True)
    prediction=import_and_predict(image,model)
    class_names = [
        'Coffee-plant', 'Cherry', 'Fox_nut(Makhana)', 'Cucumber', 'jowar',
        'Pearl_millet(bajra)', 'Olive-tree', 'chilli', 'almond', 'banana',
        'rice', 'Tobacco-plant', 'clove', 'coconut', 'cotton', 'gram', 'Lemon',
        'jute', 'maize', 'mustard-oil', 'papaya', 'soyabean', 'cardamom', 'pineapple',
        'sugarcane', 'tomato', 'tea', 'sunflower', 'vigna-radiati(Mung)', 'wheat'
    ]
    string="OUTPUT : "+class_names[np.argmax(prediction)]
    st.success(string)